### PR TITLE
Changed Opacity to show Top Bar Icons more clearly

### PR DESCRIPTION
**Pull request by kreativmind**
I have changed the opacity of the styling to allow the icons to be displayed better.

### CODE REVIEW

**Comment by Felli** [comment]
Once @ArchBlood is online to check things out we'll merge this in. :+1:

**Comment by kreativmind** [comment]
That's fine. Hope it helps.

**Review by ArchBlood — CHANGES_REQUESTED** [review]
This only affects `#topbar-second` from what I'm looking at and not `#topbar-first`? Both of these being `0.7` or even `0.6` would make things much easier.

**Comment by kreativmind** [comment]
@ArchBlood Sorry about that. I have updated as requested.

**Review by ArchBlood — APPROVED** [review]

**Comment by ArchBlood** [comment]
@kreativmind thank you. :smile:

**Pull request merged**
